### ISSUE TITLE
Bug with R 4.0.2

### ISSUE THREAD

**Issue by MatthieuB03** [greenelab/TDM#5] opened 2020-12-18 10:18 UTC
Hello, 

I have been using TDM through the function tdm_transform on R 3.6.3 and it worked fine, however, without producing an error, it produces different results when running the same code en R 4.0.2. I am providing an exemple with the test datasets provided in the package.

My code is :
sessionInfo()
tcga_tdm = tdm_transform(target_data = data.table(cbind(gene = rownames(tcga), tcga)), 
                         ref_data = data.table(cbind(gene = rownames(meta), meta)), 
                         inv_reference = T, log_target = T) 
tcga_tdm = data.matrix(tcga_tdm[, 2:101])

summary(as.vector(as.matrix(meta)))
summary(as.vector(tcga_tdm))

Under R 3.6.3 I the results is

R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tidyr_1.1.2                 mixOmics_6.10.9             lattice_0.20-41             MASS_7.3-53                 Metrics_0.1.4              
 [6] edgeR_3.28.1                limma_3.42.2                vsn_3.54.0                  plotly_4.9.2.1              VennDiagram_1.6.20         
[11] futile.logger_1.4.3         corrplot_0.84               ComplexHeatmap_2.2.0        RColorBrewer_1.1-2          pheatmap_1.0.12            
[16] reshape2_1.4.4              ggrepel_0.8.2               viridis_0.5.1               viridisLite_0.3.0           xlsx_0.6.5                 
[21] readxl_1.3.1                pxt.utils_1.0.0             PexmvdBMK_0.17.2            scales_1.1.1                binr_1.1                   
[26] data.table_1.13.2           dplyr_1.0.2                 DESeq2_1.26.0               SummarizedExperiment_1.16.1 DelayedArray_0.12.3        
[31] BiocParallel_1.20.1         matrixStats_0.57.0          Biobase_2.46.0              GenomicRanges_1.38.0        GenomeInfoDb_1.22.1        
[36] IRanges_2.20.2              S4Vectors_0.24.4            BiocGenerics_0.32.0         FactoMineR_2.3              factoextra_1.0.7           
[41] ggplot2_3.3.2               COCONUT_1.0.2               preprocessCore_1.48.0       TDM_0.3                    

loaded via a namespace (and not attached):
  [1] backports_1.2.0        circlize_0.4.11        Hmisc_4.4-1            igraph_1.2.6           plyr_1.8.6             lazyeval_0.2.2        
  [7] splines_3.6.3          digest_0.6.27          htmltools_0.5.0        fansi_0.4.1            magrittr_2.0.1         checkmate_2.0.0       
 [13] memoise_1.1.0          cluster_2.1.0          openxlsx_4.2.3         annotate_1.64.0        rARPACK_0.11-0         jpeg_0.1-8.1          
 [19] colorspace_2.0-0       blob_1.2.1             haven_2.3.1            xfun_0.19              crayon_1.3.4           RCurl_1.98-1.2        
 [25] jsonlite_1.7.1         genefilter_1.68.0      survival_3.2-7         glue_1.4.2             gtable_0.3.0           zlibbioc_1.32.0       
 [31] XVector_0.26.0         GetoptLong_1.0.4       car_3.0-10             shape_1.4.5            abind_1.4-5            futile.options_1.0.1  
 [37] DBI_1.1.0              rstatix_0.6.0          Rcpp_1.0.5             xtable_1.8-4           htmlTable_2.1.0        clue_0.3-57           
 [43] flashClust_1.01-2      foreign_0.8-76         bit_4.0.4              Formula_1.2-4          htmlwidgets_1.5.2      httr_1.4.2            
 [49] ellipsis_0.3.1         pkgconfig_2.0.3        XML_3.99-0.3           rJava_0.9-12           farver_2.0.3           nnet_7.3-14           
 [55] utf8_1.1.4             locfit_1.5-9.4         tidyselect_1.1.0       labeling_0.4.2         rlang_0.4.8            AnnotationDbi_1.48.0  
 [61] munsell_0.5.0          cellranger_1.1.0       tools_3.6.3            cli_2.2.0              generics_0.1.0         RSQLite_2.2.1         
 [67] broom_0.7.2            stringr_1.4.0          knitr_1.30             bit64_4.0.5            zip_2.1.1              admisc_0.11           
 [73] purrr_0.3.4            formatR_1.7            venn_1.9               leaps_3.1              compiler_3.6.3         rstudioapi_0.13       
 [79] curl_4.3               png_0.1-7              affyio_1.56.0          ggsignif_0.6.0         tibble_3.0.4           geneplotter_1.64.0    
 [85] stringi_1.4.6          RSpectra_0.16-0        forcats_0.5.0          Matrix_1.2-18          vctrs_0.3.5            pillar_1.4.7          
 [91] lifecycle_0.2.0        BiocManager_1.30.10    GlobalOptions_0.1.2    corpcor_1.6.9          bitops_1.0-6           R6_2.5.0              
 [97] latticeExtra_0.6-29    affy_1.64.0            gridExtra_2.3          rio_0.5.16             lambda.r_1.2.4         assertthat_0.2.1      
[103] xlsxjars_0.6.1         rjson_0.2.20           withr_2.3.0            GenomeInfoDbData_1.2.2 hms_0.5.3              rpart_4.1-15          
[109] carData_3.0-4          ggpubr_0.4.0           scatterplot3d_0.3-41   base64enc_0.1-3        ellipse_0.4.2         

> summary(as.vector(as.matrix(meta)))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.776   6.810   7.785   8.010   8.976  14.879 
> summary(as.vector(tcga_tdm))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.776   6.244   7.543   7.683   8.869  14.879 

Under R 4.0.2

R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] scales_1.1.1      binr_1.1          data.table_1.13.4 TDM_0.3          

loaded via a namespace (and not attached):
 [1] digest_0.6.27       R6_2.5.0            lifecycle_0.2.0     evaluate_0.14       rlang_0.4.9         rmarkdown_2.5      
 [7] tools_4.0.2         Biobase_2.48.0      munsell_0.5.0       tinytex_0.27        xfun_0.19           yaml_2.2.1         
[13] parallel_4.0.2      compiler_4.0.2      colorspace_2.0-0    BiocGenerics_0.34.0 htmltools_0.5.0     knitr_1.30  

> summary(as.vector(as.matrix(meta)))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.776   6.810   7.785   8.010   8.976  14.879 
> summary(as.vector(tcga_tdm))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    1.0   371.0   638.0   724.7  1054.0  1743.0 

As you can see, it seems that the results under R 4.0.2 are eroneous without producing an error.

Thanks
Best
Matt

**Comment by jeffreyat** [comment] 2021-01-06 18:18
I am going to see if I can get it updated, thanks for letting me know!

**Comment by jeffreyat** [comment] 2021-07-10 17:58
Unfortunately, I have been unable to reproduce this issue and I am getting consistent results under R 4.0.2. I'd be glad to know if anyone else is experiencing it.

**Comment by envest** [comment] 2021-07-21 13:53
Hi @jeffreyat thank you for looking into this issue. It appears I am experiencing a similar problem to what @MatthieuB03 described. I'm working with R 4.0.3 and R 3.6.3.

### My code
```
library(TDM)
sessionInfo()

data(meta)
data(tcga)

tcga_tdm = tdm_transform(target_data = data.table(cbind(gene = rownames(tcga), tcga)),
                         ref_data = data.table(cbind(gene = rownames(meta), meta)),
                         inv_reference = T, log_target = T)
tcga_tdm = data.matrix(tcga_tdm[, 2:101])

summary(as.vector(as.matrix(meta)))
summary(as.vector(tcga_tdm))
```
### With R 3.6.3
```
> library(TDM)
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] TDM_0.3

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3   
> data(meta)
> data(tcga)
> tcga_tdm = tdm_transform(target_data = data.table(cbind(gene = rownames(tcga), tcga)),
+                          ref_data = data.table(cbind(gene = rownames(meta), meta)),
+                          inv_reference = T, log_target = T)
data.table 1.12.8 using 1 threads (see ?getDTthreads).  Latest news: r-datatable.com
> tcga_tdm = data.matrix(tcga_tdm[, 2:101])
> summary(as.vector(as.matrix(meta)))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.776   6.810   7.785   8.010   8.976  14.879 
> summary(as.vector(tcga_tdm))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.776   6.244   7.543   7.683   8.869  14.879 
```

### With R 4.0.3
```
> library(TDM)
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] TDM_0.3

loaded via a namespace (and not attached):
[1] compiler_4.0.3 tools_4.0.3    tinytex_0.29   xfun_0.21     
> data(meta)
> data(tcga)
> tcga_tdm = tdm_transform(target_data = data.table(cbind(gene = rownames(tcga), tcga)),
+                          ref_data = data.table(cbind(gene = rownames(meta), meta)),
+                          inv_reference = T, log_target = T)
data.table 1.13.6 using 1 threads (see ?getDTthreads).  Latest news: r-datatable.com
> tcga_tdm = data.matrix(tcga_tdm[, 2:101])
> summary(as.vector(as.matrix(meta)))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.776   6.810   7.785   8.010   8.976  14.879 
> summary(as.vector(tcga_tdm))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      1     477     952    1015    1525    2364
```

Again, thank you, and please let me know how I can help explore this further.

--Steven

**Comment by envest** [comment] 2021-07-22 20:44
Here are the docker images I used to run in R 3.6.3 and 4.0.3:

- envest/tdm363
- envest/tdm403

They both build on a rocker/tidyverse image with `binr`, `data.table`, `scales`, and a specific commit of `greenelab/TDM` (ref: 341eb77105e7efd2654b4f112578648584936e06).

**Comment by jeffreyat** [comment] 2021-07-22 21:00
I am able to reproduce the problem now, so thanks for the info. Now I just have to figure it out! I'll let you know.

**Comment by envest** [comment] 2022-03-28 18:50
Hi! I have an update on this 😄  @jeffreyat @cgreene 

This issue is being caused by new behavior of `data.matrix()` with R version 4. I have PR that resolves the issue ready for review: https://github.com/greenelab/TDM/pull/7

Again, here is my code:
```r
library(TDM)
sessionInfo()

data(meta)
data(tcga)

tcga_tdm = tdm_transform(target_data = data.table(cbind(gene = rownames(tcga), tcga)),
                         ref_data = data.table(cbind(gene = rownames(meta), meta)),
                         inv_reference = T, log_target = T)
tcga_tdm = data.matrix(tcga_tdm[, 2:101])

summary(as.vector(as.matrix(meta)))
summary(as.vector(tcga_tdm))
```

And I'm working with updated docker images `envest/tdm363` and `envest/tdm403`. The update comes from now using my forked version of TDM where I implemented changes to TDM code.

Here are the results:

### With R-3.6.3 (no change)
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] TDM_0.3

loaded via a namespace (and not attached):
[1] compiler_3.6.3
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  4.776   6.810   7.785   8.010   8.976  14.879
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  4.776   6.244   7.543   7.683   8.869  14.879
```

### with R-4.0.3 (notice `summary()` results now agree)
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] TDM_0.3

loaded via a namespace (and not attached):
[1] compiler_4.0.3
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  4.776   6.810   7.785   8.010   8.976  14.879
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  4.776   6.244   7.543   7.683   8.869  14.879
```

**Comment by cgreene** [comment] 2022-10-18 13:58
@envest : can you verify that this is closed with #7 merged?

**Comment by envest** [comment] 2022-10-18 14:09
Yes! ready to close with #7 merged 👍

**Comment by cgreene** [comment] 2022-10-18 14:44
@MatthieuB03 - thank you for the report! @envest - thank you for the fix!

**Closed as completed by cgreene** 2022-10-18 14:44 UTC
